[package]
authors = ["Trangar <victor.koenders@gmail.com>"]
edition = "2018"
name = "trangarbot_2"
version = "0.1.0"

[dependencies]
chrono = "0.4"
failure = "0.1"
irc = "0.13"
lazy_static = "1.4"
parking_lot = "0.9"
regex = "1.3"
reqwest = "0.9"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
futures = "0.1"
url = "2.1"

